import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-gray-50 text-gray-900">
        <TRPCReactProvider>
          <div className="pb-24">
            {children}
          </div>

          {/* ボトムナビゲーション */}
          <nav className="fixed bottom-4 left-1/2 -translate-x-1/2 z-50 w-[95%] max-w-md">
            <div className="flex items-center justify-around bg-white/80 backdrop-blur-md border border-gray-200 py-3 px-6 rounded-3xl shadow-2xl">
              
              <Link href="/" className="flex flex-col items-center gap-1 group">
                <span className="text-2xl group-active:scale-90 transition-transform">📦</span>
                <span className="text-[10px] font-bold text-gray-500 group-hover:text-blue-600">在庫一覧</span>
              </Link>

              <Link href="/shopping-list" className="flex flex-col items-center gap-1 group">
                <span className="text-2xl group-active:scale-90 transition-transform">🛒</span>
                <span className="text-[10px] font-bold text-gray-500 group-hover:text-red-600">買い物</span>
              </Link>

              <Link href="/category-list" className="flex flex-col items-center gap-1 group">
                <span className="text-2xl group-active:scale-90 transition-transform">🏷️</span>
                <span className="text-[10px] font-bold text-gray-500 group-hover:text-green-600">マスタ</span>
              </Link>

            </div>
          </nav>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
